server:
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /
  port: ${PORT}
spring:
  application:
    name: eVote
  profiles:
    active: #spring.profiles.active#
  jackson:
    serialization.write_dates_as_timestamps: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: XHTML
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
evote:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers: X-Total-Count, filename
    allow-credentials: true
    max-age: 1800
  async:
    core-pool-size: 4
    max-pool-size: 100
    queue-capacity: 10000
  application:
    name: #project.name
    version: #project.version
    timestamp: #timestamp
  mail:
    from: no-reply@example.com