server:
  servlet:
    session:
      cookie:
        http-only: true
  port: 8092
spring:
  application:
    name: eVote
  profiles:
    active: #spring.profiles.active#
  jackson:
    serialization.write_dates_as_timestamps: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: XHTML
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
evote:
  async:
    core-pool-size: 4
    max-pool-size: 100
    queue-capacity: 10000
  mail:
    from: eppt-test@pajakku.com